@startuml
class HealthBar {
    + maxHealth : float
    + health : float
    Start() : void
    Update() : void
    + TakeDamage(damage:float) : void
    + Heal(healing:float) : void
    + Die() : void
}
MonoBehaviour <|-- HealthBar
HealthBar --> "healthbar" Slider
@enduml
