@startuml
class PlayerCharacter {
    + baseDamage : float = 1
    + baseSpeed : float = 10f
    + maxWeapons : int = 3
    + maxItems : int = 3
    + baseHealth : float = 100
    Start() : void
    Update() : void
    + GetPlayerDamage() : float
    + TakeDamage(damage:float) : void
    + Die() : void
}
MonoBehaviour <|-- PlayerCharacter
@enduml
