@startuml
class Player1_BasicAttack_Projectile {
    offset : float = 0
    Start() : void
    <<new>> Move(deltaTime:float, horizontalVector:float) : void
    <<new>> Update() : void
}
Projectile <|-- Player1_BasicAttack_Projectile
@enduml
